version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/todo
    command: bash -c "go build && ./todo_api_go"

  db:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: postgres:12.3
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: 'app'
      POSTGRES_PASSWORD: 'app-pass'

volumes:
  database-data:
